bind 0.0.0.0
port 6379

requirepass ${REDIS_PASSWORD}
protected-mode yes

maxmemory        512mb
maxmemory-policy allkeys-lru

appendonly no
save ""

databases 16

loglevel   notice
logfile    /var/log/redis/redis.log

timeout          300
tcp-keepalive    60

hz               10
dynamic-hz       yes